//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public byte[] salt { get; set; }
        public bool active { get; set; }
        public string resetCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
