//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCZ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCZDbContext : DbContext
    {
        public PCZDbContext()
            : base("name=PCZDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<JobIssues> JobIssues { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<VendorMessage> VendorMessage { get; set; }
        public virtual DbSet<AdminMessage> AdminMessage { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistory { get; set; }
    }
}
