//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobIssues = new HashSet<JobIssues>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public string OtherIssue { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public int VendorID { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string JobNo { get; set; }
        public string ImgUrl { get; set; }
        public int TotalCost { get; set; }
        public int OtherCharges { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<bool> CustomerPaid { get; set; }
        public Nullable<bool> CustomerDelivered { get; set; }
        public Nullable<System.DateTime> CustomerDeliveredDate { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobIssues> JobIssues { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
