//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobIssues
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int IssueId { get; set; }
        public int Cost { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Job Job { get; set; }
    }
}
