//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public int Payment_Amount { get; set; }
        public int Recieved_Amount { get; set; }
        public int Remaining_Amount { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string JobNo { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
